version: '2'
networks:
  common_network:
    name: common_network
services:

#Zookeeper Service.
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    restart: "no"
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    container_name: zookeeper
    networks:
      - common_network

#Kafka Service
  kafka1:
    image: 'confluentinc/cp-kafka:latest.arm64'
    restart: "no"
    ports:
      # - 9092:9092
      - 29091:29091
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:9092,INTERNAL://:29092
      # KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka0:29092,EXTERNAL_SAME_HOST://localhost:9092
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29091,INTERNAL://:9091
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9091,EXTERNAL_SAME_HOST://127.0.0.1:29091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    container_name: kafka1
    depends_on:
      - "zookeeper"
    networks:
      - common_network

  kafka2:
    image: 'confluentinc/cp-kafka:latest.arm64'
    restart: "no"
    ports:
      # - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:9092,INTERNAL://:29092
      # KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka0:29092,EXTERNAL_SAME_HOST://localhost:9092
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9092,EXTERNAL_SAME_HOST://127.0.0.1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - "zookeeper"
    container_name: kafka2
    networks:
      - common_network

  # kafka3:
  #   image: 'confluentinc/cp-kafka:latest.arm64'
  #   restart: "no"
  #   ports:
  #     # - 9093:9093
  #     - 29093:29093
  #   environment:
  #     KAFKA_BROKER_ID: 3
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  #     # KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:9093,INTERNAL://:29093
  #     # KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka0:29093,EXTERNAL_SAME_HOST://localhost:9093
  #     KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29093,INTERNAL://:9093
  #     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9093,EXTERNAL_SAME_HOST://127.0.0.1:29093
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  #   container_name: kafka3
  #   depends_on:
  #     - "zookeeper"
  #   networks:
  #     - common_network

  # kafka4:
  #   image: 'confluentinc/cp-kafka:latest.arm64'
  #   restart: "no"
  #   ports:
  #     # - 9094:9094
  #     - 29094:29094
  #   environment:
  #     KAFKA_BROKER_ID: 4
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  #     # KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:9094,INTERNAL://:29094
  #     # KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka4:29094,EXTERNAL_SAME_HOST://localhost:9094
  #     KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29094,INTERNAL://:9094
  #     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:9094,EXTERNAL_SAME_HOST://127.0.0.1:29094
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  #   container_name: kafka4
  #   depends_on:
  #     - "zookeeper"
  #   networks:
  #     - common_network

