version: '2'
networks:
  common_network:
    name: common_network
services:

#Maria DB
  mariadb:
    container_name: mariadb
    image: mariadb:10.5.9
    environment: 
      - MYSQL_ROOT_PASSWORD=spark
      - MYSQL_USER=spark
      - MYSQL_PASSWORD=spark
      - MYSQL_DATABASE=sparkde
    ports: 
      - '3306:3306'
    networks:
      - common_network